name: release

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Get version from tag
        id: tag_name
        run: |
          echo "${{ github.event.workflow_run.head_branch }}"

          FULL_TAG="${{ github.event.workflow_run.head_branch }}"

          echo ${FULL_TAG}

          VERSION="${FULL_TAG#v}"

          echo ${VERSION}

          TAG_MESSAGE=$(git tag -l --format='%(contents)' "${FULL_TAG}")

          echo ${TAG_MESSAGE}

          echo "current_version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag_message=${TAG_MESSAGE}" >> $GITHUB_OUTPUT

      - name: Get Changelog Entry
        id: reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          path: dist/
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ github.event.workflow_run.head_branch }} ${{ steps.tag_name.outputs.tag_message }}"
          body: ${{ steps.reader.outputs.changes }}
          tag_name: ${{ github.event.workflow_run.head_branch }}
          files: dist/*
          prerelease: ${{ contains(github.event.workflow_run.head_branch, '-') }}
