name: release

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Changelog Entry
        id: reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: ${{ github.event.workflow_run.head_branch }}
          path: ./CHANGELOG.md

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          path: dist/
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.reader.outputs.changes }}
          tag_name: ${{ github.event.workflow_run.head_branch }}
          files: dist/*
          prerelease: ${{ contains(github.event.workflow_run.head_branch, '-') }}
